### ISSUE TITLE
QUESTION

### ISSUE THREAD

**Issue by ZEROX7** [JTK222/Global-Packs#15]
hey ther since i cant comment on curseforge i will use this page.
for datapack and resource pack do they NEED to be in a zip or can they be in a folder curseforge has rejected my modpack because it had zips inside it XD

**Comment by JTK222** [comment]
They can be a folder too, but when you're using datapacks from curseforge, please consider just adding them like a resource pack.
(the mod will recognize them by default)
If it's your custom ones, you're free to just leave them as a folder.
If you don't have any further questions, I'll close this issue in 1-2 days.
