### ISSUE TITLE
pointing at specific files doesnt work

### ISSUE THREAD

**Issue by VastayanWings** [JTK222/Global-Packs#16]
i wanted to define global ressourcepacks for my modpack, however since curseforge requires them to be put into the ressources folder and since 2 other mods add their own packs (legacy/own programmers art) into the folder as well i tried to point at the files directly

they do not forceload themself at all. only time they do is when only the directory is specified (and yes i added the .zip to the filenames in config)

version 1.18.2 |

**Comment by JTK222** [comment]
Thank you two, fixed in 1.12.2.2 for 1.18-1.18.2 and 1.14.2 for 1.19+ respectively ^^
