### ISSUE TITLE
[Fabric 1.18.2] RS Compat Datapacks loaded by Global Packs do not apply

### ISSUE THREAD

**Issue by TelepathicGrunt** [JTK222/Global-Packs#17]
A user came to me saying my RS compat datapacks were not working. I attempt to reproduce the issue and found that when Global Packs is the one to add the datapack to the world, the RS structures do not get changed. If I add the datapacks manually to the world by hadn without Global Packs, the datapacks transforms RS's structures just fine. Oddly enough, /datapack list enabled showed the compat datapacks as active when Global packs was adding them but they did not actually do anything.

Repro steps:

**Mods to add:**
- https://www.curseforge.com/minecraft/mc-mods/repurposed-structures-fabric
- https://www.curseforge.com/minecraft/mc-mods/feature-nbt-deadlock-be-gone
- https://www.curseforge.com/minecraft/mc-mods/cloth-config
- https://www.curseforge.com/minecraft/mc-mods/drp-global-datapack
- https://www.curseforge.com/minecraft/mc-mods/yungs-api-fabric
- https://www.curseforge.com/minecraft/mc-mods/yungs-better-desert-temples-fabric
- https://www.curseforge.com/minecraft/mc-mods/yungs-better-dungeons-fabric
- https://www.curseforge.com/minecraft/mc-mods/yungs-better-witch-huts-fabric

**Datapacks to add:**
- https://www.curseforge.com/minecraft/texture-packs/repurposed-structures-better-desert-temples-compat
- https://www.curseforge.com/minecraft/texture-packs/repurposed-structures-better-strongholds-datapack
- https://www.curseforge.com/minecraft/texture-packs/repurposed-structures-better-dungeons-datapack
- https://www.curseforge.com/minecraft/texture-packs/repurposed-structures-better-witch-huts-compat

User /locate command to go to witch huts, pyramids, strongholds from RS to see if they were properly transformed or not by the datapacks.

Log with Global Packs that has no errors:
[latest.log](https://github.com/JTK222/Global-Packs/files/9465206/latest.log)

**Comment by TelepathicGrunt** [comment]
note I have not tested other minecraft versions or modloaders. Don't have enough energy to do that right now

**Comment by MechanosG** [comment]
Yikes.  This might explain why I'm having so much trouble with my 1.19.2 Quilt modpack.  I was attempting to use Global Packs to override another mod's datapack, in order to remove some recipes (they don't provide a config and want people to use datapacks to change things).  But for some reason the recipes keep showing back up.  I now suspect this issue is probably the problem.  Priority is being given to the original mod, so my changes do nothing.

Any luck looking into this @JTK222 ?

**Comment by JTK222** [comment]
The issue still exists, but it only affects world gen related features and not recipes.
I have already fixed it for 1.18 though, and should really look into fixing it for 1.19 too

**Comment by JTK222** [comment]
This issue has been fixed for 1.19 and 1.19.3
