### ISSUE TITLE
Shaderpack support

### ISSUE THREAD

**Issue by SylisMC** [JTK222/Global-Packs#19]
~~Global shaderpack folder would be an awesome tie in for iris~~

Edit: I had also made the suggestion on the discord server, after making this post so I figured I'd better explain here to avoid confusion.

I'm suggesting a global shader pack folder outside of the game directory, allowing you to have one copy of your shader packs accessible from all of your instances.

**Comment by JTK222** [comment]
To many different mods, handle shaderpacks in way to many different ways.
Therefore, this won't be implemented, I recommend you to request this feature directly for shader mods.
They do not need to support Global Packs, just their own global folder.
