### ISSUE TITLE
[Bug] Bootcrash MC-1.19.2 GP-1.14.3

### ISSUE THREAD

**Issue by SylisMC** [JTK222/Global-Packs#24]
global_packs-fabric-1.19.2-1.14.3_fabric.jar

fabric-api-0.69.0+1.19.2.jar
Exit code: 1 [latest.log](https://github.com/JTK222/Global-Packs/files/10233167/latest.log)

fabric-api-0.69.0+1.19.2.jar ❌Crashed
fabric-api-0.68.0+1.19.2.jar ❌Crashed
fabric-api-0.67.1+1.19.2.jar ❌Crashed
fabric-api-0.67.0+1.19.2.jar ❌Crashed
fabric-api-0.66.0+1.19.2.jar ❌Crashed
fabric-api-0.64.0+1.19.2.jar ❌Crashed

having config files pre-generated did not make a difference 

global_packs-fabric-1.19.2-1.14.2_fabric.jar appears crash free on all versions

**Comment by JTK222** [comment]
Fixed in 1.14.2.1 thanks for reporting.
I need to somehow make a tool to check this for me, I've made this exact issue so often already >.<

**Comment by SylisMC** [comment]
Good to know
