### ISSUE TITLE
[Quilt-1.19.3] v1.15 Load resourcepacks has datapacks

### ISSUE THREAD

**Issue by un-pogaz** [JTK222/Global-Packs#29]
On the new v1.15 for Quilt-1.19.3, the resourcepacks has loaded in the datapacks selection screen.
This resourcepacks are in ".minecraft/resourcepacks"

v1.15
![2022-12-27_08 22 19](https://user-images.githubusercontent.com/46523284/209628547-473d932d-70e2-44e2-b727-ee74a467a24a.png)

previous v1.14.2 on Quilt-1.19.2 (expected)
![2022-12-27_08 25 06](https://user-images.githubusercontent.com/46523284/209628567-a9ef6ae2-79b9-4c0e-86ff-75f839768746.png)

**Comment by JTK222** [comment]
Thanks for your report, will be fixed in v1.15.2
I am checking for further bugs first and will try to fix them before I publish this.

**Comment by JTK222** [comment]
v1.15.2 is released and approved
