### ISSUE TITLE
Question - Does this also work with just unzipped folders?

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [JTK222/Global-Packs#30]
Curse is being a pain - I needed to redistro a resource after some heavy edits for my specific pack on 1.19.2 - does global pack have the power to read the folder tree or only zips? 

![hfbqcoN 1](https://user-images.githubusercontent.com/10351221/221583505-cdf4004d-bb28-40ef-b616-ba943922f55f.png)

**Comment by JTK222** [comment]
Yes, it does.
