### ISSUE TITLE
(Dedicated) server usage

### ISSUE THREAD

**Issue by vico93** [JTK222/Global-Packs#33]
How can i specify what optional datapacks should be loaded in a dedicated server?

Can i use `initial-enabled-packs` in server.properties for that case?

**Comment by JTK222** [comment]
initial-enabled-packs is for datapacks that are enabled, when the world is generated.
This is necessary for worldgen datapacks.
Dedicated servers aren't directly supported by the mod, as it's not necessary (they can only use a single datapack directory anyways, and resourcepacks don't work at all).
But people have told me that it works with dedicated servers, which is nice, but as I said, not officially supported.
