### ISSUE TITLE
datapacks/ should be in the required datapacks in the config by default

### ISSUE THREAD

**Issue by ilovehorrorcats** [JTK222/Global-Packs#35]
It will keep resourcepacks and datapacks separate and it is easier to have a global datapacks folder

**Comment by JTK222** [comment]
Having them separate is not compatible with 3rd party launchers.
Minecraft has no standard folder, and launchers cannot rely on such mods to add that folder.
That's the only reason the resourcepacks folder is in the list for datapacks,
this is the only allowed way for modpacks on curseforge, to properly use many various datapacks.
Additionally, inside the global_packs folder, there are already separate folders for data and resource packs.
