### ISSUE TITLE
wrong modrinth description

### ISSUE THREAD

**Issue by SinyoMinyo** [JTK222/Global-Packs#36]
on modrinth the folders are:
global_packs/required_datapacks
global_packs/optional_datapacks
global_packs/resourcepacks

in the config the folders are:
global_packs/required_resources/
global_packs/required_data/
global_packs/optional_data/

folders also did not auto generate so people that dont read the config file use the wrong folders

**Comment by JTK222** [comment]
Thanks for bringing this to my attention. I fixed it and added a note that those are different based on your version.
