### ISSUE TITLE
Crash when opening minecraft

### ISSUE THREAD

**Issue by AKM112** [JTK222/Global-Packs#40]
I am making a modpack.
And before adding this mod it was opening normally.

The game crashed whilst initializing game
Error: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
termination code: -1

[crash-log.txt](https://github.com/JTK222/Global-Packs/files/12579502/crash-log.txt)

**Comment by JTK222** [comment]
Either you're using a wrong version of Global Packs, or there is a mod incompatibility.
If you send me your normal log, I can check which of the two it is.
Alternatively a mod list might work too.

**Comment by AKM112** [comment]
There you go

[modlist.txt](https://github.com/JTK222/Global-Packs/files/12580109/modlist.txt)

**Comment by AKM112** [comment]
By the way there is only one version of Global Packs for 1.19.2

**Comment by JTK222** [comment]
> By the way there is only one version of Global Packs for 1.19.2

Yes but no. There are also 4 different versions for 1.19.2, though they are hidden on Curseforge. (Still obtainable if you know how to/your pack is old enough)
All visible on Modrinth though.
Thanks for the modlist, I'll try the latest versions of all those mods together tomorrow after work and let you know when I find something.

**Comment by Smellsin** [comment]
After a bit of testing it seems like an issue with the [Create: New Age](https://modrinth.com/mod/create-new-age) mod, after facing the same issue with my modpack and disabling each mod one by one that I had similarly with the poster.
