### ISSUE TITLE
PSA: for modpack creators, this mod will not work if you're trying to publish your modpack

### ISSUE THREAD

**Issue by LordDecay26** [JTK222/Global-Packs#42]
just so you guys know, curseforge will reject your project if you try using this mod in your modpack on the basis that the resourcepacks / datapacks within the global packs folder are not referenced in the JSON. they will not let you use this mod for it's intended purpose in modpacks.
![image](https://github.com/JTK222/Global-Packs/assets/27246075/17b250b9-5f05-42ef-9bc6-992d207d5371)

**Comment by LordDecay26** [comment]
update: if you take it to curseforge support, after doing some back and fourth with the support team generally the support team will be able to manually approve your project , just be aware that using this mod in your modpack within the curseforge enviornment will be a huge hassle.

**Comment by JTK222** [comment]
If you're installing any Resource-/Datapacks that are available on curseforge, do not move them to any other folder.
Leave them in the resourcepacks folder, this is one of the default folders solely for this reason.

To go into detail: 
Reposting any files, that exists on CF already, is a rule violation.
This includes Data- and Resourcepacks, however curseforge will treat those just like mods.
Meaning that if you do it correctly* they will not be inside your overrides directory on export, but will be linked in the manifest.
All launchers will just download the packs from this manifest, and you won't have any issues with approval.

As this is a common mistake, I have just added a disclaimer to the Curseforge page that explains this.

* The correct way in this case, is to not move packs outside the "resourcepacks" folder.
It's a stupid folder for datapacks, but it's what curseforge has chosen, 
and to my knowledge, this mod is the only one that will load Datapacks from that folder.

**Comment by LordDecay26** [comment]
you are mistaken, if you leave them in the resourcepacks folder, they do not get loaded by default.

**Comment by JTK222** [comment]
I think I know the default config quite well.
https://github.com/JTK222/Global-Packs/blob/dev/1.19/Common/src/main/resources/default_config.toml#L21
However this is only true for datapacks, resourcepacks need to be added manually,
as doing otherwise, could break stuff when people install their own resourcepacks.
So you're partially right.
