### ISSUE TITLE
global_packs-forge-1.20.2-1.20.1-1.16.3.jar crashes with Forge 48.0.40 during start

### ISSUE THREAD

**Issue by Doktor42** [JTK222/Global-Packs#45]
Crashes immediately after pressing "play" in the launcher - no mojang screen.
No other mods added.
No entry in log.
No crash-report created.
Simply Exit Code -1 in the Launcher.
Forge without the mod starts fine

**Comment by JTK222** [comment]
I have tested the version with Forge 48.0.34 and it worked there.
I'll take a look at it tomorrow after work and try to figure out what broke.

**Comment by JTK222** [comment]
Thanks for the report, I found the issue and am currently waiting for Curseforge to approve it, it's version 1.16.4 for 1.20.2
https://legacy.curseforge.com/minecraft/mc-mods/drp-global-datapack/files/4907095
