### ISSUE TITLE
Datapack in the 'resourcepacks' folder are loader and cannot be disable

### ISSUE THREAD

**Issue by un-pogaz** [JTK222/Global-Packs#55]
When you put a datapack in the `resourcepacks` folder, the datapack is load at the same way than if it had been in `global_packs/required_data`, load it for all worlds, without the possibility of deactivating it.

Expected behavior: datapack in the `resourcepacks` folder should not be loaded.

Version: Quilt 20.3.1 and Quilt 21.0.0

**Comment by JTK222** [comment]
Works as intended, this behavior is mandatory for Curseforge. If you don't want them all to be force loaded, make use of the config, that's what it's for.

**Comment by un-pogaz** [comment]
Ah. \**Cursed words toward Curseforge*\*

Okay, thanks, I edited my config file.

PS: The Modrinth page (where I come from) don't have a warning about this behavior, so I recomend to add one.
