### ISSUE TITLE
Global Packs for 1.20.1?

### ISSUE THREAD

**Issue by Looodon** [JTK222/Global-Packs#56]
Hi, 
Will the mod be available for 1.20.1? I tried "Global Packs - Forge - 1.19.4 - v1.16.2," but it crashes on startup so i switched to "Global Packs - Forge 1.20.2 - v1.16.4" and "Global Packs - Forge - v20.3.1", but they don't work either.  Most mods are available for 1.20.1 but not higher so I'm stuck on it sadly

**Comment by JTK222** [comment]
The 1.19.4 version works for 1.20.1, usually when it crashes, it's because one of the datapacks isn't compatible.
If you provide me a crash log I can check what the issue is specifically.

**Comment by Looodon** [comment]
thank you for offering to help, you were right! all sorted!
