### ISSUE TITLE
Warning with latest.log mentioning Global packs doesn't follow the recommended Semantic Versioning/ incompatible

### ISSUE THREAD

**Issue by TheShadyyOneYT** [JTK222/Global-Packs#57]
![Screenshot 2024-08-16 151639](https://github.com/user-attachments/assets/9dd4d69a-5664-494c-8081-9cfaa130386b)

It still works in-game but this is a warning, and it could most likely be fixed.

### disregard what I said, I'm just a dumbass and realized it doesn't matter.

**Comment by TheShadyyOneYT** [comment]
Global Pack's Version: 
![Screenshot 2024-08-16 151847](https://github.com/user-attachments/assets/8917a00a-1fba-4cbe-9929-a07968095265)

Fabric API Version: 0.92.2
Modloader Version (Fabric): 0.16.0
Game Version: 1.20.1

Full Modlist:
![Screenshot 2024-08-16 150100](https://github.com/user-attachments/assets/3978cf93-356d-47ff-a551-e68cb0af523f)
![Screenshot 2024-08-16 150113](https://github.com/user-attachments/assets/b4aa2c6a-9e48-4c9b-8942-83dca0ebbc29)
![Screenshot 2024-08-16 150121](https://github.com/user-attachments/assets/0662f767-abce-4810-8eaf-39a8de20a727)
![Screenshot 2024-08-16 150130](https://github.com/user-attachments/assets/4f4cc393-cb35-4449-850e-715b382d8360)

**Comment by JTK222** [comment]
To explain this, yeah Fabric is not a huge fan of the version, however semantic versioning is not suited for mutli loader mods.
If I'd follow semantic versioning properly, I wouldn't be able to tell if people try to use the forge mod on fabric, or vice versa, which happens regularly.
If I could, I'd turn this warning off, but it's sadly not possible.
