### ISSUE TITLE
Modpack not getting accepted

### ISSUE THREAD

**Issue by Dzserbo** [JTK222/Global-Packs#62]
This is not an issue with the 1.20.1 modpack in itself, it is just that whenever I submit my modpack which contains this mod, it gets rejected, because: The following files belong to CurseForge-hosted projects, and should therefore not be added directly to zip files:
overrides/mods/global_packs-forge-1.19.4-1.16.2_forge (1).jar

**Comment by JTK222** [comment]
Delete the file, install the mod trough the CF app, and re-export your pack, then CF will recognize the mod properly.
